name: build
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/checkout@v7
        with:
          repository: "makryl/SDL"
          ref: "emscripten-openfile-dialog"
          path: "external/SDL-release-3.4.16"

      - uses: actions/checkout@v7
        with:
          repository: "makryl/nes-test-roms"
          ref: "add-more-tests"
          path: "external/nes-test-roms"

      - uses: emscripten-core/setup-emsdk@v15
        with:
          version: "5.0.7"

      - name: SDL3 deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends build-essential git make \
          pkg-config cmake ninja-build libasound2-dev libpulse-dev \
          libaudio-dev libfribidi-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
          libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
          libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
          libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libthai-dev libusb-1.0-0-dev \
          libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev to that command line

      - name: build
        run: ./release.sh

      - uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist/Emscripten-Release"

      - uses: actions/deploy-pages@v4

      - name: release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create latest --prerelease --clobber --title "MyaowNES Latest" \
            --notes "Auto build from main branch. Update time: $(date -u +'%Y-%m-%d %H:%M:%S UTC')." \
            myaownes_latest_linux_x64.zip \
            myaownes_latest_windows_x64.zip \
            myaownes_latest_wasm32.zip
